vscode:
  extensions:
    - foam.foam-vscode@0.3.1:P8HCgNxHOkgriyD+IloBCw==
    - esbenp.prettier-vscode@5.7.1:GDba64T6G+TUi1qmc6BE3A==
    - yzhang.markdown-all-in-one@3.3.0:fRpb0skkyto7j5ibdwKGTA==
    - kortina.vscode-markdown-notes@0.0.20:DHCx8TmaA9qZjJ3FvratKA==
    - tchayen.markdown-links@0.8.0:Nyecfp+aJ6WO57GUBbT3Qg==
    - philipbe.theme-gray-matter@1.6.0:hPBj+aYkp8C5KH/j2ayvTQ==